apiVersion: apps/v1
kind: Deployment
metadata:
  name: convert-tmp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: convert-tmp
  template:
    metadata:
      labels:
        app: convert-tmp
    spec:
      containers:
      - name: convert-tmp
        image: mrsilvacosta/conver-tmp:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: convert
spec:
  selector:
    app: convert-tmp
  ports:
  - port: 8080
    targetPort: 8080
